### ISSUE TITLE
Collect and print stdout output from command that builds downstream dependencies

### ISSUE THREAD

**Issue by msridhar** [ucr-riple/NullAwayAnnotator#205]
This is the code that runs the command for building downstream dependencies:

https://github.com/ucr-riple/NullAwayAnnotator/blob/6740c7db40199fb7a57b831934f1d66629015af9/annotator-core/src/main/java/edu/ucr/cs/riple/core/util/Utility.java#L70-L85

It collects the stderr output from the command, but not the stdout.  It would be good to have a way to collect and print stdout as well, for diagnosing issues.  Also, the current logic looks a bit weird.  There is a `while` loop that spins collecting the stderr output.  I think this loop should run until the process terminates (otherwise you may miss some output).  But if it runs until the process terminates, then I think the `p.waitFor()` call is unnecessary?  We may just want to switch to code like this:

https://stackoverflow.com/a/12200361/1126796

With Redirect.INHERIT we will get the printing of stdout / stderr for free.  (Or possibly we want to redirect stderr of the child process to stdout, and then just send everything to our stdout.)

**Comment by nimakarimipour** [comment]
@msridhar Thank you very much for reporting the issue and the suggestion, will work on the PR now.
