### ISSUE TITLE
Repeated annotations and broken formatting when adding suppressions

### ISSUE THREAD

**Issue by lazaroclapp** [ucr-riple/NullAwayAnnotator#77]
**Describe the bug**
When running the auto-annotator on suppression (and `@NullUnmarked`) adding mode, I am observing two issues on fields that otherwise already contain annotations:

- Duplicated instances of `@Nullable` added
- Lack of spaces between the last added annotation and the field's modifiers

For example, this is the initial code:

```
@JsonProperty
@JsonInclude(JsonInclude.Include.NON_NULL)
public String foo;
```

And this the auto-annotator's result (before Google Java Format, but that's irrelevant for now because this code won't build):

```
@JsonProperty @JsonInclude(JsonInclude.Include.NON_NULL) @Nullable @SuppressWarnings("NullAway.Init")
@Nullablepublic   String foo;
```

Note: a) `@Nullable` is repeated, despite it already having `@SuppressWarnings("NullAway.Init")` (which makes no sense combined with `@Nullable`); b) `@Nullablepublic` as opposed to `@Nullable public`

**To Reproduce**
See code-example above. Configuration includes `--chain --activate-downstream-dependencies-analysis --force-resolve`.

**Expected behavior**
I would expect that field to either be annotated:

```
@JsonProperty
@JsonInclude(JsonInclude.Include.NON_NULL)
@SuppressWarnings("NullAway.Init")
public String foo;
```

Or:

```
@JsonProperty
@JsonInclude(JsonInclude.Include.NON_NULL)
@Nullable
public String foo;
```

**Stack trace**
N/A

**OS (please complete the following information):**
 - OS: Linux
 - Annotator Version : this [commit](https://github.com/nimakarimipour/NullAwayAnnotator/pull/76/commits/d6e965f109a9a2e9436de4714b0ab15032a7fb20), currently the head of #76

**Comment by nimakarimipour** [comment]
#90 is landed and resolves this issue.
